### ISSUE TITLE
Summarise number of GBIF records for each Ecosytem service cateogry

### ISSUE THREAD

**Issue by JamesDMSpeed** [JamesDMSpeed/GhanaEcoServices#5]

**Comment by sarahay2017** [comment]
James is yet to provide a script to fix this issue

**Comment by JamesDMSpeed** [comment]
I have changed to using the Tazonstand package to lookup accepted names for species not matching to the GBIF dataset. There are a few species that still do not match, but this is most likely as they are absent in the GBIF dataset in Ghana (e.g. Allium sativum, Aloe vera - plants with obvious uses).
What we need to do next is to merge these names with the matching names into a column that can be used to link the uses dataset with the gbif records.

**Comment by sarahay2017** [comment]
Issue fixed with the help of Stuart
