### ISSUE TITLE
Using taxize to match species names to GBIF data

### ISSUE THREAD

**Issue by JamesDMSpeed** [JamesDMSpeed/GhanaEcoServices#6]
I wrote some script in the summary Ghana.plant.uses.exploration.R file to match species names with names in the GBIF data. There were around 130 species that did not match. Some of these were encoding issues, others synonyms or spelling errors.
I used the taxize package tnrs function to find accepted names for these 130. This seems to work in some cases, but errors come up with encoding issues. Once they are fixed we should be able to simply link the species list we have with the GBIF data. 

This needs to be looked more into...

**Comment by JamesDMSpeed** [comment]
Sarah and I have fixed the encoding issues. This leaves us with around 95 species that do no t have GBIF data. The taxize package suggests that some of these may have other accepted names. @sarahay2017 will check to see if there is GBIF data for these species under the alternative names.

**Comment by sarahay2017** [comment]
There is data for most of the species but their authority names were missing in the papers. I am checking with the map in GBIF to see which of them are available in Ghana.

**Comment by sarahay2017** [comment]
Closing issue after using taxise to match species names to GBIF data
