### ISSUE TITLE
Tuning maxent with bio, landcover and population data using Ghana example analyses script

### ISSUE THREAD

**Issue by sarahay2017** [JamesDMSpeed/GhanaEcoServices#8]
It tunes with only the bio data but unfortunately, it does not when land cover and population data are added

**Comment by JamesDMSpeed** [comment]
The population data is not on the repo. The tuning works fine on my machine with landcover and climate.

**Comment by sarahay2017** [comment]
Population data is now on the repo.

**Comment by JamesDMSpeed** [comment]
Can you add the GhanaPopData.gri file in addition to the .grd file

**Comment by sarahay2017** [comment]
GhanaPopData.gri has been added

**Comment by JamesDMSpeed** [comment]
Fixed issue by ensuring the background data was drawn from raster of same extent as environmental data
